# Generated by Django 5.0.4 on 2026-03-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('normal', 'Normal'), ('hard', 'Hard'), ('insane', 'Insane')], default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
