# Generated by Django 5.0.4 on 2026-03-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_achievement_activitylog_dailystreak_gamesession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
